language: go

sudo: required

services:
  - docker

install:
  - docker run --rm -v "$PWD":/go/src/github.com/aotallabs/frisket -w /go/src/github.com/aotallabs/frisket instrumentisto/glide install
deploy:
  provider: script
  script: deploy.sh
  skip_cleanup: true
  on:
    branch: master
